/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.1.232.1
    Soft IP Version: 1.0.1
    2022 05 15 01:03:19
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module icePLL (ref_clk_i, rst_n_i, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  outcore_o;
    output  outglobal_o;
endmodule