OUT     = $(OBJ_DIR)/fos.prg
S_SRCS += main.s
S_SRCS += sdcard.s
S_SRCS += fat32.s

EMU_PARAMS = -sdcard /c/Work/x16/x16-emulator/disk5.img -scale 2 -quality nearest -echo

include common/Makefile.common
